// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: docker2nix/v1alpha1/generate.proto

package docker2nixv1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Dockerfile  *string                `protobuf:"bytes,1,opt,name=dockerfile"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GenerateRequest) Reset() {
	*x = GenerateRequest{}
	mi := &file_docker2nix_v1alpha1_generate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRequest) ProtoMessage() {}

func (x *GenerateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docker2nix_v1alpha1_generate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GenerateRequest) GetDockerfile() string {
	if x != nil {
		if x.xxx_hidden_Dockerfile != nil {
			return *x.xxx_hidden_Dockerfile
		}
		return ""
	}
	return ""
}

func (x *GenerateRequest) SetDockerfile(v string) {
	x.xxx_hidden_Dockerfile = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *GenerateRequest) HasDockerfile() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GenerateRequest) ClearDockerfile() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Dockerfile = nil
}

type GenerateRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Dockerfile *string
}

func (b0 GenerateRequest_builder) Build() *GenerateRequest {
	m0 := &GenerateRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Dockerfile != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Dockerfile = b.Dockerfile
	}
	return m0
}

type GenerateResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Nix         *string                `protobuf:"bytes,1,opt,name=nix"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GenerateResponse) Reset() {
	*x = GenerateResponse{}
	mi := &file_docker2nix_v1alpha1_generate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateResponse) ProtoMessage() {}

func (x *GenerateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docker2nix_v1alpha1_generate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GenerateResponse) GetNix() string {
	if x != nil {
		if x.xxx_hidden_Nix != nil {
			return *x.xxx_hidden_Nix
		}
		return ""
	}
	return ""
}

func (x *GenerateResponse) SetNix(v string) {
	x.xxx_hidden_Nix = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *GenerateResponse) HasNix() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GenerateResponse) ClearNix() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Nix = nil
}

type GenerateResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Nix *string
}

func (b0 GenerateResponse_builder) Build() *GenerateResponse {
	m0 := &GenerateResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Nix != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Nix = b.Nix
	}
	return m0
}

var File_docker2nix_v1alpha1_generate_proto protoreflect.FileDescriptor

const file_docker2nix_v1alpha1_generate_proto_rawDesc = "" +
	"\n" +
	"\"docker2nix/v1alpha1/generate.proto\x12\x13docker2nix.v1alpha1\"1\n" +
	"\x0fGenerateRequest\x12\x1e\n" +
	"\n" +
	"dockerfile\x18\x01 \x01(\tR\n" +
	"dockerfile\"$\n" +
	"\x10GenerateResponse\x12\x10\n" +
	"\x03nix\x18\x01 \x01(\tR\x03nix2l\n" +
	"\x11Docker2NixService\x12W\n" +
	"\bGenerate\x12$.docker2nix.v1alpha1.GenerateRequest\x1a%.docker2nix.v1alpha1.GenerateResponseB\xe8\x01\n" +
	"\x17com.docker2nix.v1alpha1B\rGenerateProtoP\x01ZQgithub.com/unstoppablemango/docker2nix/pkg/docker2nix/v1alpha1;docker2nixv1alpha1\xa2\x02\x03DXX\xaa\x02\x13Docker2nix.V1alpha1\xca\x02\x13Docker2nix\\V1alpha1\xe2\x02\x1fDocker2nix\\V1alpha1\\GPBMetadata\xea\x02\x14Docker2nix::V1alpha1b\beditionsp\xe9\a"

var file_docker2nix_v1alpha1_generate_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_docker2nix_v1alpha1_generate_proto_goTypes = []any{
	(*GenerateRequest)(nil),  // 0: docker2nix.v1alpha1.GenerateRequest
	(*GenerateResponse)(nil), // 1: docker2nix.v1alpha1.GenerateResponse
}
var file_docker2nix_v1alpha1_generate_proto_depIdxs = []int32{
	0, // 0: docker2nix.v1alpha1.Docker2NixService.Generate:input_type -> docker2nix.v1alpha1.GenerateRequest
	1, // 1: docker2nix.v1alpha1.Docker2NixService.Generate:output_type -> docker2nix.v1alpha1.GenerateResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_docker2nix_v1alpha1_generate_proto_init() }
func file_docker2nix_v1alpha1_generate_proto_init() {
	if File_docker2nix_v1alpha1_generate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_docker2nix_v1alpha1_generate_proto_rawDesc), len(file_docker2nix_v1alpha1_generate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_docker2nix_v1alpha1_generate_proto_goTypes,
		DependencyIndexes: file_docker2nix_v1alpha1_generate_proto_depIdxs,
		MessageInfos:      file_docker2nix_v1alpha1_generate_proto_msgTypes,
	}.Build()
	File_docker2nix_v1alpha1_generate_proto = out.File
	file_docker2nix_v1alpha1_generate_proto_goTypes = nil
	file_docker2nix_v1alpha1_generate_proto_depIdxs = nil
}
